### ISSUE TITLE
LAVD has slowdowns

### ISSUE THREAD

**Issue by Pogogo007** [CachyOS/CachyOS-Handheld#15]
Currently LAVD has performance issues causing slowdowns and low framerates.

Wait for LAVD to fix upstream or disable scx.service to disable it (will be disabled by default soon)

**Comment by Pogogo007** [comment]
Probably related to [this issue](https://github.com/sched-ext/scx/issues/296)

**Comment by Pogogo007** [comment]
Possibly fixed with latest LAVD

**Comment by erkexzcx** [comment]
My feedback:

It's not fixed (on desktops), or it's only applicable to handheld consoles?

Yesterday I've tried using LAVD with `Helldivers 2`. As soon as I loaded into the match, it became lagfest - quickly running `sudo systemctl disable --now scx` (switched back to BORE) fixed the lag mid-game and I was able to continue playing perfectly. :man_shrugging:

**Comment by ptr1337** [comment]
> My feedback:
> 
> It's not fixed (on desktops), or it's only applicable to handheld consoles?
> 
> Yesterday I've tried using LAVD with `Helldivers 2`. As soon as I loaded into the match, it became lagfest - quickly running `sudo systemctl disable --now scx` (switched back to BORE) fixed the lag mid-game and I was able to continue playing perfectly. 🤷‍♂️

What is the output of:
`sudo dmesg | grep setup_percpu`

Actually, it would need to be tested with scx-scheds-git.

**Comment by erkexzcx** [comment]
>  `sudo dmesg | grep setup_percpu`
```
[    0.050611] setup_percpu: NR_CPUS:320 nr_cpumask_bits:24 nr_cpu_ids:24 nr_node_ids:1
```

> it would need to be tested with scx-scheds-git

Yep, tested below with this package.

Specs (it's Arch, but converted to CachyOS):
![image](https://github.com/CachyOS/CachyOS-Handheld/assets/5955795/b00efb2f-6842-4430-a4a2-ffcb384a4fce)

LAVD:
![image](https://github.com/CachyOS/CachyOS-Handheld/assets/5955795/0f4547c0-cb11-42a6-aae0-9b38d58aa198)

BORE (no scx):
![image](https://github.com/CachyOS/CachyOS-Handheld/assets/5955795/8c63d10a-1c84-41b8-81e2-c83efaa85fbe)

I assume that LAVD should also work on desktop gaming? Because I've tested it on desktop and this repo is for handhelds only... :pray:

**Comment by erkexzcx** [comment]
Well, LAVD does not seem to use all cores fairly :thinking: 
![image](https://github.com/CachyOS/CachyOS-Handheld/assets/5955795/816111c2-8f35-40da-a342-fadf2c21ac2b)

Tried installing and starting `irqbalance` but that did not change anything...

**Comment by erkexzcx** [comment]
> Note that scx_lavd currently is not optimized for multi-CCX/NUMA architectures.

Quick google says:

> comes with eight physical cores spread across two four-core Core Complexes (CCXes).

Alright, these above tests are invalid... :facepalm:

**Comment by ateaz** [comment]
Just to tack on an idea I have: LAVD's core compaction could potentially affect benchmark results, so it might be prudent to test it with `--no-core-compaction` in future to rule out any impact that might have.

**Comment by Pogogo007** [comment]
Seems to have been resolved in newer LAVD versions. Very cool.
