### ISSUE TITLE
MSI Claw 8 AI+ (Intel Ultra 7 258V) post sleep controller issues

### ISSUE THREAD

**Issue by eaglemmoomin** [CachyOS/CachyOS-Handheld#68]
Hi I installed CachyOS-Handheld edition the other day on my Claw. I have pin code entry setup on wake from sleep and boot. I'm seeing the face buttons/controls all work as expected on boot. But on wake from sleep most of the controller buttons are not functioning. I can get past the pin code screen via the touch screen however at that point the machine is treating the right joystick as a mouse. X and A buttons work. Nothing else is registered. Does a way exist to force the machine back to using the all of the face buttons etc?

Restarting the machine it's fine again. I haven't installed hand held daemon which is something I might try as I saw something saying input plumber and HHD don't coexist well.

**Comment by eaglemmoomin** [comment]
Very difficult to say at the moment with the other recent cock up that prevents gamemode starting properly on MSI Claws. I get a black screen on boot that requires starting a sddm session up from one of the other ttys and then switching back over. I've noticed that gamemode seems very unstable currently after the workaround. Dropping to desktop still works more reliably. So I don't see the point in testing the resume functionality as it's not in a stable place generally right now.

**Comment by 1Naim** [comment]
> Very difficult to say at the moment with the other recent issue that prevents gamemode starting properly on MSI Claws. I get a black screen on boot that requires starting a sddm session up from one of the other ttys and then switching back over

I think this should be fixed now with the latest gamescope update, can you confirm?

**Comment by eaglemmoomin** [comment]
However the issues on waking from sleep still exist. Not as bad but the left joystick now behaves as a mouse, the right joystick seems fine. The H/W volume buttons seem ok. But the B and Y buttons are not working correctly along with I think the triggers (I'll have to double check those). So it's better but not quite right.

I'm going to put HandHeld Daemon back onto the Claw. Close but no cigar at the moment.

**Comment by simiscoool-afk** [comment]
what is the status of this issue? seems like you forgot to close if i read the last comment right.

**Comment by eaglemmoomin** [comment]
As far as I know it's still a problem. I installed Bazzite 43 onto the device in the end as it's a bit less fiddling. Recently updated to 44 on the device. Why is this relevant to Cachy you ask. Bazzite is now running Input Plumber after the fallout with HHDs maintainer. The issues with controls after a resume still exist, ie joypad becomes mouse input, B button working and so on. I'm going to put CachyOS handheld edition back on it to see if that makes any difference.  The only reliable method I've seen so far is to use HHD. So I suspect I'll have to set that back up after some testing.


I suspect this is the underlying issue https://github.com/ShadowBlip/InputPlumber/issues/722
